version: '3.1'

services:

  pagadiarioDB:
    container_name: pagadiarioDB
    platform: linux/amd64
    restart: unless-stopped
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - pagadiariodbvolume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: pagadiarioDB
    ports:
      - 8080:8080

volumes:
  pagadiariodbvolume:
